version: '3.8'

services:
  # Backend Laravel
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=DATN
      - DB_USERNAME=root
      - DB_PASSWORD=root
    networks:
      - app-network

  # Frontend ReactJS
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: dev  # <<< Build từ stage dev trong Dockerfile
    container_name: react_frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app          # <<< Mount mã nguồn từ local vào container
      - /app/node_modules        # <<< Tránh xung đột thư viện node_modules
    depends_on:
      - backend
    networks:
      - app-network


  # MySQL Database
  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=DATN
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - app-network

  # Laravel Migration Service (chạy thủ công khi cần)
  migrate:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - db
    command: php artisan migrate --force
    volumes:
      - ./backend:/var/www/html
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
